# Event Level Cuts

maxVz: 100.0          # cm, |Vz| < maxVz
maxVr: 2.0            # cm, Vr < maxVr
minRefMult: 0.0       # Minimum RefMult
maxRefMult: 1000.0    # Maximum RefMult
maxVzDiff: 3.0        # cm, |Vz_TPC - Vz_VPD| < maxVzDiff (pileup rejection)
maxAbsVzVpd: 200.0    # cm; use VPD (hVzDiff / vzDiff cut) only when |vzVpd| < this

