# Main configuration file for Lambda (V0) analysis (auau19_anaLambda)
# common
event:         cuts/event/event_auau19_anaLambda.yaml
track:         cuts/track/track.yaml
pid:           cuts/pid/pid.yaml
v0:            cuts/v0reco/v0.yaml
mixing:        cuts/mixing/mixing.yaml

#maker
lambda:        maker/maker_auau19_anaLambda.yaml

#hist
hist:          hist/hist_auau19_anaLambda.yaml

#analysis info
analysis:      analysis/analysis_info_temp.yaml
