# Analysis Information (Phi, auau19_anaPhi)

starTag:
  triggerSets: "production_19GeV_2019"
  stream: "st_physics"
  collision: "auau19"
  year: "year2019"
  productionTag: "P24iy"
  libraryTag: "SL24y"
  filetype: "daq_reco_picoDst"
  filenameFilter: "st_physics"
  storageExclude: "HPSS"

dataset:
  collisionSystem: "Au+Au"
  allPicoDstList: "picoDstList/auau19GeV.list"
  runRange:
    min: 19000000
    max: 20000000
  goodRunList: ""
  dataQuality: "production"
  dataFormat: "picoDst"

analysis:
  anaName: &anaName "auau19_anaPhi_temp"
  name: *anaName
  type: "resonance"
  targetParticle: "phi"
  decayChannel: "K+K-"
  workDir: "/star/u/$USER/Path/To/star-analyzer"
  baseRunMacro: "run_anaPhi"
  baseAnaMacro: "anaPhi"
  mainConf: "mainconf/main_auau19_anaPhi.yaml"
  jobName: *anaName
  scratchSubdir: *anaName
  outputFileStem: *anaName
  nFiles: 40

analyst:
  name: "User Name"
  institute: "Tohoku University"
  email: "user.email@institute.jp"
